// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nutrition_app_backend.Data;

#nullable disable

namespace nutrition_app_backend.Migrations
{
    [DbContext(typeof(WaoDbContext))]
    [Migration("20260506153844_AddFoodAndLoggingModule")]
    partial class AddFoodAndLoggingModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.FoodLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<decimal>("CaloriesKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("InputMethod")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<byte>("MealTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("QuantityG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId", "LogDate")
                        .HasDatabaseName("idx_logs_user_date");

                    b.ToTable("food_logs", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.MealType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("meal_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            NameVi = "Bữa sáng"
                        },
                        new
                        {
                            Id = (byte)2,
                            NameVi = "Bữa trưa"
                        },
                        new
                        {
                            Id = (byte)3,
                            NameVi = "Bữa tối"
                        },
                        new
                        {
                            Id = (byte)4,
                            NameVi = "Bữa phụ"
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.WeightLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("idx_weight_user_date");

                    b.ToTable("weight_logs", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodCategory", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("food_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            NameEn = "Rice dishes",
                            NameVi = "Cơm & Xôi"
                        },
                        new
                        {
                            Id = (byte)2,
                            NameEn = "Noodle soups",
                            NameVi = "Phở & Bún"
                        },
                        new
                        {
                            Id = (byte)3,
                            NameEn = "Bread & Pastries",
                            NameVi = "Bánh mì & Bánh"
                        },
                        new
                        {
                            Id = (byte)4,
                            NameEn = "Beverages",
                            NameVi = "Đồ uống"
                        },
                        new
                        {
                            Id = (byte)5,
                            NameEn = "Packaged food",
                            NameVi = "Thực phẩm đóng gói"
                        },
                        new
                        {
                            Id = (byte)6,
                            NameEn = "Vegetables & Fruits",
                            NameVi = "Rau củ quả"
                        },
                        new
                        {
                            Id = (byte)7,
                            NameEn = "Meat & Seafood",
                            NameVi = "Thịt & Hải sản"
                        },
                        new
                        {
                            Id = (byte)8,
                            NameEn = "F&B Chains",
                            NameVi = "Chuỗi F&B"
                        },
                        new
                        {
                            Id = (byte)9,
                            NameEn = "International",
                            NameVi = "Quốc tế"
                        },
                        new
                        {
                            Id = (byte)10,
                            NameEn = "Other",
                            NameVi = "Khác"
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<ulong?>("ActiveImageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("Barcode")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("NameEn")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("ServingSizeG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ServingUnitVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveImageId")
                        .IsUnique()
                        .HasDatabaseName("idx_food_active_image");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_food_status");

                    b.HasIndex("NameVi", "NameEn")
                        .HasDatabaseName("idx_food_ft")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.ToTable("food_items", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemComponent", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<Guid>("ChildFoodId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("ParentFoodId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("QuantityG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChildFoodId");

                    b.HasIndex("ParentFoodId", "ChildFoodId")
                        .IsUnique();

                    b.ToTable("food_item_components", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemImage", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId")
                        .HasDatabaseName("idx_img_food");

                    b.ToTable("food_item_images", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodNutrition", b =>
                {
                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("CaloriesKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("FiberG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("SodiumMg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("SugarG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FoodItemId");

                    b.ToTable("food_nutrition", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserAuthProvider", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUid")
                        .IsUnique();

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("ActivityLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("BmrKcal")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("GoalType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal?>("GoalWeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TargetCalories")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TargetCarbsG")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TargetFatG")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TargetProteinG")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TdeeKcal")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.FoodLog", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithMany("FoodLogs")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Diaries.MealType", "MealType")
                        .WithMany("FoodLogs")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("MealType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.WeightLog", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItem", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItemImage", "ActiveImage")
                        .WithOne()
                        .HasForeignKey("nutrition_app_backend.Models.Foods.FoodItem", "ActiveImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutrition_app_backend.Models.Foods.FoodCategory", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "Creator")
                        .WithMany("CreatedFoods")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveImage");

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemComponent", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "ChildFood")
                        .WithMany("ComponentsAsChild")
                        .HasForeignKey("ChildFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "ParentFood")
                        .WithMany("ComponentsAsParent")
                        .HasForeignKey("ParentFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildFood");

                    b.Navigation("ParentFood");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemImage", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithMany("Images")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodNutrition", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithOne("Nutrition")
                        .HasForeignKey("nutrition_app_backend.Models.Foods.FoodNutrition", "FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserAuthProvider", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserGoal", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserProfile", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("nutrition_app_backend.Models.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.MealType", b =>
                {
                    b.Navigation("FoodLogs");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodCategory", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ComponentsAsChild");

                    b.Navigation("ComponentsAsParent");

                    b.Navigation("FoodLogs");

                    b.Navigation("Images");

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("CreatedFoods");

                    b.Navigation("FoodLogs");

                    b.Navigation("Goals");

                    b.Navigation("Profile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
