// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using nutrition_app_backend.Data;

#nullable disable

namespace nutrition_app_backend.Migrations
{
    [DbContext(typeof(WaoDbContext))]
    [Migration("20260601031012_AddUserPushToken")]
    partial class AddUserPushToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.FoodLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<decimal>("CaloriesKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("InputMethod")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("MealTypeId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("QuantityG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MealTypeId");

                    b.HasIndex("UserId", "LogDate")
                        .HasDatabaseName("idx_logs_user_date");

                    b.ToTable("food_logs", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.MealType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("meal_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            NameVi = "Bữa sáng"
                        },
                        new
                        {
                            Id = (byte)2,
                            NameVi = "Bữa trưa"
                        },
                        new
                        {
                            Id = (byte)3,
                            NameVi = "Bữa tối"
                        },
                        new
                        {
                            Id = (byte)4,
                            NameVi = "Bữa phụ"
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.StepLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<decimal>("CaloriesBurnedKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<byte?>("Provider")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("StepGoal")
                        .HasColumnType("int");

                    b.Property<int>("Steps")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("idx_steps_user_date");

                    b.ToTable("step_logs", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.WeightLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("idx_weight_user_date");

                    b.ToTable("weight_logs", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal>("MetValue")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_exercise_category");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_exercise_status");

                    b.ToTable("exercises", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9426),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/chay_bo_i0xdol.jpg",
                            MetValue = 8.0m,
                            NameEn = "Running",
                            NameVi = "Chạy bộ",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9430)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9435),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/di_bo_zttbcb.jpg",
                            MetValue = 3.5m,
                            NameEn = "Walking",
                            NameVi = "Đi bộ",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9436)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9438),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/dap_xe_ydjkou.jpg",
                            MetValue = 7.5m,
                            NameEn = "Cycling",
                            NameVi = "Đạp xe",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9439)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9442),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732740/boi_loi_ia9sol.jpg",
                            MetValue = 9.0m,
                            NameEn = "Swimming",
                            NameVi = "Bơi lội",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9442)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9445),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732743/nhay_day_deaept.jpg",
                            MetValue = 12.0m,
                            NameEn = "Jump Rope",
                            NameVi = "Nhảy dây",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9445)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000014"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9448),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732743/luot_song_omzllo.jpg",
                            MetValue = 3.0m,
                            NameEn = "Surfing",
                            NameVi = "Lướt sóng",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9448)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000015"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9452),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/khieu_vu_wpukmv.jpg",
                            MetValue = 4.5m,
                            NameEn = "Dancing",
                            NameVi = "Khiêu vũ",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9452)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000016"),
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9454),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732740/aerobic_dm9nsd.jpg",
                            MetValue = 7.0m,
                            NameEn = "Aerobics",
                            NameVi = "Aerobic",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9455)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9457),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732743/nang_ta_miloiy.jpg",
                            MetValue = 6.0m,
                            NameEn = "Weight Training",
                            NameVi = "Nâng tạ",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9458)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000007"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9460),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/hit_dat_elcd4c.jpg",
                            MetValue = 8.0m,
                            NameEn = "HIIT",
                            NameVi = "HIT (High Intensity Training)",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9461)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000008"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9464),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/gap_bung_g2js1l.jpg",
                            MetValue = 8.0m,
                            NameEn = "Sit-ups",
                            NameVi = "Gập bụng",
                            Status = (byte)1,
                            Unit = "reps",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9464)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000010"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9468),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732740/plank_k0rbjk.jpg",
                            MetValue = 4.0m,
                            NameEn = "Plank",
                            NameVi = "Plank",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9468)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000017"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9471),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732743/leo_nui_im09ry.jpg",
                            MetValue = 8.0m,
                            NameEn = "Climbing",
                            NameVi = "Leo núi",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9471)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000018"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9474),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732743/keo_xa_vlicau.jpg",
                            MetValue = 8.0m,
                            NameEn = "Pull-ups",
                            NameVi = "Kéo xà",
                            Status = (byte)1,
                            Unit = "reps",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9474)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000019"),
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9477),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732741/squat_pcgt35.jpg",
                            MetValue = 5.0m,
                            NameEn = "Squat",
                            NameVi = "Squat",
                            Status = (byte)1,
                            Unit = "reps",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9477)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000009"),
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9480),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/yoga_bitlo9.jpg",
                            MetValue = 3.0m,
                            NameEn = "Yoga",
                            NameVi = "Yoga",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9480)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000011"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9483),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732741/bong_da_pcibi3.jpg",
                            MetValue = 10.0m,
                            NameEn = "Football/Soccer",
                            NameVi = "Bóng đá",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9483)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000012"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9486),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/cau_long_sxihz6.jpg",
                            MetValue = 7.0m,
                            NameEn = "Badminton",
                            NameVi = "Cầu lông",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9486)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000013"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9489),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732741/bong_ro_zmldle.jpg",
                            MetValue = 8.0m,
                            NameEn = "Basketball",
                            NameVi = "Bóng rổ",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9489)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000020"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9492),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/golf_zj5sbo.jpg",
                            MetValue = 4.5m,
                            NameEn = "Golf",
                            NameVi = "Golf",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9492)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000021"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9496),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732742/tennis_pcqhh5.jpg",
                            MetValue = 7.0m,
                            NameEn = "Tennis",
                            NameVi = "Tennis",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9496)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000022"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9499),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732741/truot_van_rxlkn5.jpg",
                            MetValue = 5.0m,
                            NameEn = "Skateboarding",
                            NameVi = "Trượt ván",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9499)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000023"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9502),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732741/bong_chay_uiwjae.jpg",
                            MetValue = 5.0m,
                            NameEn = "Baseball",
                            NameVi = "Bóng chày",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9503)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000024"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9506),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732741/bong_chuyen_v6us4w.jpg",
                            MetValue = 4.0m,
                            NameEn = "Volleyball",
                            NameVi = "Bóng chuyền",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9507)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000025"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9509),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732740/pickle_ball_ciqj11.jpg",
                            MetValue = 6.0m,
                            NameEn = "Pickleball",
                            NameVi = "Pickle Ball",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9510)
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000026"),
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9512),
                            IconUrl = "https://res.cloudinary.com/drsgmoufr/image/upload/v1779732740/bong_ban_kgbyqe.jpg",
                            MetValue = 4.0m,
                            NameEn = "Table Tennis",
                            NameVi = "Bóng bàn",
                            Status = (byte)1,
                            Unit = "minutes",
                            UpdatedAt = new DateTime(2026, 6, 1, 3, 10, 9, 817, DateTimeKind.Utc).AddTicks(9513)
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.ExerciseCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("exercise_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            NameEn = "Cardio",
                            NameVi = "Cardio"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            NameEn = "Strength",
                            NameVi = "Sức mạnh"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            NameEn = "Yoga & Pilates",
                            NameVi = "Yoga & Pilates"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            NameEn = "Sports",
                            NameVi = "Thể thao"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            NameEn = "Other",
                            NameVi = "Khác"
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.ExerciseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("CaloriesBurned")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("Intensity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("UserId", "LogDate")
                        .HasDatabaseName("idx_exercise_logs_user_date");

                    b.ToTable("exercise_logs", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodCategory", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("NameEn")
                        .HasColumnType("longtext");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("food_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            NameEn = "Rice dishes",
                            NameVi = "Cơm & Xôi"
                        },
                        new
                        {
                            Id = (byte)2,
                            NameEn = "Noodle soups",
                            NameVi = "Phở & Bún"
                        },
                        new
                        {
                            Id = (byte)3,
                            NameEn = "Bread & Pastries",
                            NameVi = "Bánh mì & Bánh"
                        },
                        new
                        {
                            Id = (byte)4,
                            NameEn = "Beverages",
                            NameVi = "Đồ uống"
                        },
                        new
                        {
                            Id = (byte)5,
                            NameEn = "Packaged food",
                            NameVi = "Thực phẩm đóng gói"
                        },
                        new
                        {
                            Id = (byte)6,
                            NameEn = "Vegetables & Fruits",
                            NameVi = "Rau củ quả"
                        },
                        new
                        {
                            Id = (byte)7,
                            NameEn = "Meat & Seafood",
                            NameVi = "Thịt & Hải sản"
                        },
                        new
                        {
                            Id = (byte)8,
                            NameEn = "F&B Chains",
                            NameVi = "Chuỗi F&B"
                        },
                        new
                        {
                            Id = (byte)9,
                            NameEn = "International",
                            NameVi = "Quốc tế"
                        },
                        new
                        {
                            Id = (byte)10,
                            NameEn = "Other",
                            NameVi = "Khác"
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<ulong?>("ActiveImageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Barcode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("NameEn")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("ServingSizeG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("ServingUnitVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveImageId")
                        .IsUnique()
                        .HasDatabaseName("idx_food_active_image");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_food_status");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("idx_food_cursor_pagination");

                    b.HasIndex("NameVi", "NameEn")
                        .HasDatabaseName("idx_food_ft")
                        .HasAnnotation("MySql:FullTextIndex", true);

                    b.ToTable("food_items", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemComponent", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<Guid>("ChildFoodId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("ParentFoodId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("QuantityG")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChildFoodId");

                    b.HasIndex("ParentFoodId", "ChildFoodId")
                        .IsUnique();

                    b.ToTable("food_item_components", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemImage", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StorageProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId")
                        .HasDatabaseName("idx_img_food");

                    b.ToTable("food_item_images", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodNutrition", b =>
                {
                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("CaloriesKcal")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("FatG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("FiberG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal?>("SodiumMg")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal?>("SugarG")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("FoodItemId");

                    b.ToTable("food_nutrition", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.Menu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_menu_user");

                    b.ToTable("menus", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.MenuFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("MenuId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("QuantityG")
                        .HasColumnType("decimal(8, 2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("MenuId", "FoodItemId")
                        .IsUnique();

                    b.ToTable("menu_foods", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Data")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("idx_notif_user_created");

                    b.HasIndex("UserId", "IsRead")
                        .HasDatabaseName("idx_notif_user_read");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameVi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("notification_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MEAL_REMINDER",
                            Description = "Nhắc nhở ghi nhật ký bữa ăn",
                            NameEn = "Meal Reminder",
                            NameVi = "Nhắc nhở bữa ăn"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EXERCISE_REMINDER",
                            Description = "Nhắc nhở ghi nhật ký tập luyện",
                            NameEn = "Exercise Reminder",
                            NameVi = "Nhắc nhở tập luyện"
                        },
                        new
                        {
                            Id = 3,
                            Code = "WEIGHT_LOG_REMINDER",
                            Description = "Nhắc nhở ghi lại cân nặng",
                            NameEn = "Weight Log Reminder",
                            NameVi = "Nhắc nhở cân nặng"
                        },
                        new
                        {
                            Id = 4,
                            Code = "WATER_REMINDER",
                            Description = "Nhắc nhở uống nước",
                            NameEn = "Water Reminder",
                            NameVi = "Nhắc nhở uống nước"
                        },
                        new
                        {
                            Id = 5,
                            Code = "GOAL_ACHIEVED",
                            Description = "Thông báo khi đạt mục tiêu",
                            NameEn = "Goal Achieved",
                            NameVi = "Đạt mục tiêu"
                        },
                        new
                        {
                            Id = 6,
                            Code = "DAILY_SUMMARY",
                            Description = "Tổng kết dinh dưỡng và tập luyện trong ngày",
                            NameEn = "Daily Summary",
                            NameVi = "Tổng kết ngày"
                        },
                        new
                        {
                            Id = 7,
                            Code = "WEEKLY_REPORT",
                            Description = "Báo cáo tiến độ hàng tuần",
                            NameEn = "Weekly Report",
                            NameVi = "Báo cáo tuần"
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.UserNotificationSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DaysOfWeek")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReminderTime")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId", "NotificationTypeId")
                        .IsUnique()
                        .HasDatabaseName("idx_user_notif_setting_unique");

                    b.ToTable("user_notification_settings", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.UserPushToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("idx_push_token_unique");

                    b.HasIndex("UserId");

                    b.ToTable("user_push_tokens", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HashedToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.StreakFreezeTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FreezeDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint unsigned");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FreezeDate")
                        .IsUnique()
                        .HasDatabaseName("idx_freeze_user_date");

                    b.ToTable("streak_freeze_transactions", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("StoreTransactionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("idx_subscription_user_status");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.SubscriptionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("CHAR(36)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("subscription_events", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("subscription_plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "FREE",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 99999,
                            Name = "Gói Miễn Phí",
                            Price = 0m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Code = "MONTHLY_PREMIUM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 30,
                            Name = "Premium 1 Tháng",
                            Price = 59000m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Code = "YEARLY_PREMIUM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationDays = 365,
                            Name = "Premium 1 Năm",
                            Price = 499000m,
                            UpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserAuthProvider", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("hashed_password");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderUid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Provider", "ProviderUid")
                        .IsUnique();

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("ActivityLevel")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("BmrKcal")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("GoalType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal?>("GoalWeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("TargetCalories")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<decimal>("TargetCarbsG")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TargetFatG")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TargetProteinG")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TdeeKcal")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<decimal>("WeeklyGoalKg")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_goals", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserHealthConnection", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<byte>("Provider")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime?>("ConnectedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("UserId", "Provider");

                    b.ToTable("user_health_connections", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<byte>("Gender")
                        .HasColumnType("tinyint unsigned");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserStreak", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<int>("FreezeCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLogDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("user_streaks", (string)null);
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.FoodLog", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithMany("FoodLogs")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Diaries.MealType", "MealType")
                        .WithMany("FoodLogs")
                        .HasForeignKey("MealTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("MealType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.StepLog", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("StepLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.WeightLog", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.Exercise", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Exercises.ExerciseCategory", "Category")
                        .WithMany("Exercises")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.ExerciseLog", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Exercises.Exercise", "Exercise")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("ExerciseLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItem", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItemImage", "ActiveImage")
                        .WithOne()
                        .HasForeignKey("nutrition_app_backend.Models.Foods.FoodItem", "ActiveImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutrition_app_backend.Models.Foods.FoodCategory", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "Creator")
                        .WithMany("CreatedFoods")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActiveImage");

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemComponent", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "ChildFood")
                        .WithMany("ComponentsAsChild")
                        .HasForeignKey("ChildFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "ParentFood")
                        .WithMany("ComponentsAsParent")
                        .HasForeignKey("ParentFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildFood");

                    b.Navigation("ParentFood");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItemImage", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithMany("Images")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodNutrition", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithOne("Nutrition")
                        .HasForeignKey("nutrition_app_backend.Models.Foods.FoodNutrition", "FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.Menu", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("Menus")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.MenuFood", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Foods.FoodItem", "FoodItem")
                        .WithMany("MenuFoods")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Foods.Menu", "Menu")
                        .WithMany("MenuFoods")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.Notification", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Notifications.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.UserNotificationSetting", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Notifications.NotificationType", "NotificationType")
                        .WithMany("UserSettings")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("NotificationSettings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.UserPushToken", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("PushTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.RefreshToken", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.StreakFreezeTransaction", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("StreakFreezeTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.Subscription", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.SubscriptionPlan", "Plan")
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.SubscriptionEvent", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserAuthProvider", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserGoal", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserHealthConnection", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithMany("HealthConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserProfile", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("nutrition_app_backend.Models.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.UserStreak", b =>
                {
                    b.HasOne("nutrition_app_backend.Models.Users.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("nutrition_app_backend.Models.Users.UserStreak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Diaries.MealType", b =>
                {
                    b.Navigation("FoodLogs");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.Exercise", b =>
                {
                    b.Navigation("ExerciseLogs");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Exercises.ExerciseCategory", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodCategory", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.FoodItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ComponentsAsChild");

                    b.Navigation("ComponentsAsParent");

                    b.Navigation("FoodLogs");

                    b.Navigation("Images");

                    b.Navigation("MenuFoods");

                    b.Navigation("Nutrition");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Foods.Menu", b =>
                {
                    b.Navigation("MenuFoods");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Notifications.NotificationType", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("UserSettings");
                });

            modelBuilder.Entity("nutrition_app_backend.Models.Users.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("CreatedFoods");

                    b.Navigation("ExerciseLogs");

                    b.Navigation("FoodLogs");

                    b.Navigation("Goals");

                    b.Navigation("HealthConnections");

                    b.Navigation("Menus");

                    b.Navigation("NotificationSettings");

                    b.Navigation("Notifications");

                    b.Navigation("Profile");

                    b.Navigation("PushTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("StepLogs");

                    b.Navigation("Streak");

                    b.Navigation("StreakFreezeTransactions");

                    b.Navigation("Subscriptions");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
